name: python_script_runner
description: Flutter app that runs a Python script using a captured photo
version: 1.0.0
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
